apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-db-deployment # Sets Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-db-postgres
  template:
    metadata:
      labels:
        app: user-db-postgres
    spec:
      containers:
      - name: postgres
        image: postgres # Sets Image
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432 # Exposes container port
        # envFrom:
        #   - configMapRef:
        #       name: postgres-config
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: "1"
        - name: POSTGRES_DB
          value: fu-capstone-user
        volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: user-db-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: user-db # Sets service name
  labels:
    app: user-db-postgres # Labels and Selectors
spec:
  selector:
    app: user-db-postgres
  ports:
    - port: 5432 # Sets port to run the postgres application
      targetPort: 5432
  type: ClusterIP # Sets service type 
